apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp-cluster
spec:
  bgpInstances:
    - name: instance-64512
      localASN: 64512
      peers:
        - name: peer-to-mikrotik
          peerASN: 64512
          peerAddress: 192.168.88.1
          peerConfigRef:
            name: cilium-bgp-peer
